# Generated by Django 3.2.4 on 2021-08-18 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalImagesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('lead_image', models.ImageField(upload_to='portal_images')),
                ('lead_image_summary', models.CharField(max_length=60)),
                ('post_text_content', models.TextField()),
                ('image_1', models.ImageField(upload_to='portal_images')),
                ('image_1_summary', models.CharField(max_length=60)),
                ('image_2', models.ImageField(upload_to='portal_images')),
                ('image_2_summary', models.CharField(max_length=60)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='portal_images')),
                ('image_3_summary', models.CharField(blank=True, max_length=60)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='portal_images')),
                ('image_4_summary', models.CharField(blank=True, max_length=60)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='portal_images')),
                ('image_5_summary', models.CharField(blank=True, max_length=60)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='portal_images')),
                ('image_6_summary', models.CharField(blank=True, max_length=60)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='portal_images')),
                ('image_7_summary', models.CharField(blank=True, max_length=60)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='portal_images')),
                ('image_8_summary', models.CharField(blank=True, max_length=60)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PortalTextPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('lead_image', models.ImageField(upload_to='portal_images')),
                ('lead_image_summary', models.CharField(max_length=60)),
                ('text_content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PortalVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('lead_image', models.ImageField(upload_to='portal_images')),
                ('lead_image_summary', models.CharField(max_length=60)),
                ('video_url', models.URLField()),
                ('text_content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
