# Generated by Django 3.2.4 on 2021-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210818_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalimagespost',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='portaltextpost',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='portalvideopost',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
    ]
