# Generated by Django 3.2.4 on 2021-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210818_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_1_summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_2_summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_3_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_4_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_5_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_6_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_7_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='image_8_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='lead_image_summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portaltextpost',
            name='lead_image_summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portalvideopost',
            name='lead_image_summary',
            field=models.CharField(max_length=200),
        ),
    ]
