# Generated by Django 3.2.4 on 2021-08-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210818_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalimagespost',
            old_name='post_text_content',
            new_name='text_content',
        ),
    ]
