# Generated by Django 3.2.4 on 2021-08-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_imagespostcomment_textpostcomment_videopostcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagespostcomment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='textpostcomment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='videopostcomment',
            old_name='post_id',
            new_name='post',
        ),
    ]
