# Generated by Django 3.2.4 on 2021-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210818_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalimagespost',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='portalimagespost',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='portaltextpost',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='portaltextpost',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='portalvideopost',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='portalvideopost',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
