# Generated by Django 3.2.4 on 2021-07-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_street_address1',
            new_name='default_street_address_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='default_street_address2',
            new_name='default_street_address_2',
        ),
    ]
