# Generated by Django 3.2.4 on 2021-08-07 10:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210705_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
