# Generated by Django 3.2.4 on 2021-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_default_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
