# Generated by Django 3.2.4 on 2021-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210807_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='default_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
    ]
