# Generated by Django 3.2.4 on 2021-08-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210807_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_street_address_1',
            new_name='default_street_address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='default_street_address_2',
            new_name='default_street_address2',
        ),
    ]
