# Generated by Django 3.2.4 on 2021-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210812_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
