# Generated by Django 3.2.4 on 2021-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
