# Generated by Django 3.2.4 on 2021-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_pic.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
