# Generated by Django 3.2.4 on 2021-08-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_album_year'),
        ('checkout', '0005_auto_20210804_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('cd', 'CD'), ('vinyl', 'Vinyl')], max_length=5)),
                ('quantity', models.IntegerField()),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.album')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumlineitems', to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('l', 'L')], max_length=1, null=True)),
                ('quantity', models.IntegerField()),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlineitems', to='checkout.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
