# Generated by Django 3.2.4 on 2021-06-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('tracklist', models.JSONField()),
                ('cd_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vinyl_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
                ('spotify_url', models.URLField()),
            ],
        ),
    ]
