# Generated by Django 3.2.4 on 2021-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField(choices=[('clothing', 'Clothing'), ('other', 'Other')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
