# Generated by Django 3.2.4 on 2021-06-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
