# Generated by Django 3.2.4 on 2021-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210703_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='album_covers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='missing_item.jpg', upload_to='product_images'),
        ),
    ]
