# Generated by Django 3.2.4 on 2021-08-02 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210703_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1985, message='The year must be at least 1985'), django.core.validators.MaxValueValidator(2050, message='The year must be less than 2050')]),
        ),
    ]
