# Generated by Django 3.2.4 on 2021-06-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('video_url', models.URLField()),
                ('spotify_url', models.URLField()),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.album')),
            ],
        ),
    ]
