# Generated by Django 3.2.4 on 2021-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_single_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
