# Generated by Django 3.2.4 on 2021-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0008_alter_comment_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
