# Generated by Django 3.2.4 on 2021-08-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_album_slug'),
        ('media_app', '0010_alter_single_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='single',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='singles', to='shop.album'),
        ),
    ]
