# Generated by Django 3.2.4 on 2021-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0011_auto_20210806_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
