# Generated by Django 3.2.4 on 2021-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0012_alter_single_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
    ]
